### ISSUE TITLE
driver = dovecot via inetd instead of unix socket

### ISSUE THREAD

**Issue by ser** [Exim/exim#32]
Currently `driver = dovecot` is able to communicate with the authorisation server only via a unix socket. In a bigger WAN deployments it is very inefficient, as it requires to for example using `socat` to "encapsulate" unix socket into TCP or UDP. 

My issue is to ask for making possible of specifying an address like "10.77.33.44:7743" for the communication with the authorisation service via TCP.

More about the driver: http://wiki2.dovecot.org/HowTo/EximAndDovecotSASL

**Comment by philpennock** [comment]
A reasonable request and a patch or PR implementing this is likely to be merged (as long as it looks secure and updates the doc source too).

**Comment by philpennock** [comment]
For clarity: I am not saying that such a patch is in the works on our end; I'm saying that were we to see one, we'd likely take it.  Exim is a pure-volunteer project.
