### ISSUE TITLE
Main website says latest version is 4.86 + GitHub Changelog says 4.87

### ISSUE THREAD

**Issue by davidfavor** [Exim/exim#36]
Let me know if the GitHub Changelog applies to "next release", rather than current release.

Thanks.

**Comment by philpennock** [comment]
The changelog is storing up the items for the next release, as you suspected.

We tag all releases, with PGP-signed tags, so GitHub will helpfully show them to you when you visit https://github.com/Exim/exim/releases -- so you can see that 4.86 is the latest released version.

**Comment by davidfavor** [comment]
Thanks.
