### ISSUE TITLE
remove relay-test.mail-abuse.org from docs

### ISSUE THREAD

**Issue by jahir** [Exim/exim#37]
mail-abuse.org was taken over by TrendMicro (in 2011, AFAIK) and relay-test.mail-abuse.org is non-functional now, so we should remove it from the docs.
I don't know any relay-test that is accessible via telnet, but there are some web-based ones listed in https://listi.jpberlin.de//pipermail/postfixbuch-users/2012-January/057832.html

**Comment by nigelm** [comment]
Docs edited and references removed in 86d5230bb79219ec69786ff5b9add4306d31e986
